<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE student [
    <!ELEMENT student (name+,class,age*,section)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT class (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
    <!ELEMENT section (#PCDATA)>
]>
<student>
    <name>Ayyaz khan</name>
    <name>Ayyaz khan</name>
    <class>10</class>
    <age>26</age>
    <age>26</age>
    <age>26</age>
    <section>b</section>
</student>